name       : robin-map
version    : 0.6.3
release    : 1
source     :
    - https://github.com/Tessil/robin-map/archive/v0.6.3.tar.gz : e6654c8c2598f63eb0b1d52ff8bdf39cfcc91d81dd5d05274a6dca91241cd72f
license    : MIT
homepage   : https://github.com/Tessil/robin-map/
component  : programming.library
summary    : C++ implementation of a fast hash map and hash set using robin hood hashing
description: |
    The robin-map library is a C++ implementation of a fast hash map and hash set using open-addressing and linear robin hood hashing with backward shift deletion to resolve collisions.
patterns   :
    - /* 
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
