name       : robin-map
version    : 1.0.1
release    : 2
source     :
    - https://github.com/Tessil/robin-map/archive/v1.0.1.tar.gz : b2ffdb623727cea852a66bddcb7fa6d938538a82b40e48294bb581fe086ef005
license    : MIT
homepage   : https://github.com/Tessil/robin-map/
component  : programming.library
summary    : C++ implementation of a fast hash map and hash set using robin hood hashing
description: |
    The robin-map library is a C++ implementation of a fast hash map and hash set using open-addressing and linear robin hood hashing with backward shift deletion to resolve collisions.
patterns   :
    - /*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
